version: '3.9'
services:
  minio:
    image: minio/minio:latest
    container_name: keremet-chat-minio
    volumes:
      - minio_storage:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  minio_storage: {}