version: '3.9'
services:
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    profiles:
      - monitoring
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
    profiles:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/./provisioning/dashboards:/etc/grafana/dashboards
      - grafana-data:/var/lib/grafana
  minio:
    image: minio/minio:latest
    container_name: keremet-chat-minio
    volumes:
      - minio_storage:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  grafana-data:
    external: true
  prom_data:
  minio_storage: {}