server:
  servlet:
    session:
      cookie:
        http-only: false
  port: 8081
logging:
  level:
    org.springframework:
      web.socket: debug
      web: DEBUG
      security: trace

spring:
  main:
    banner-mode: off
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: 3600000
  session:
    timeout: 43200m
  liquibase:
    database-change-log-lock-table: db_changelog_lock
    database-change-log-table: db_changelog
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
    contexts: test
  security:
    oauth2:
      client:
        registration:
          github:
            common-provider-type: github
            provider: github
            client-name: GitHub
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
        provider:
          github:
            user-name-attribute: login
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/keremet_chat

app:
  cors:
    allowCredentials: true
    allowedOrigins: http://localhost:5173/,http://localhost:4200/
    allowedMethods: GET,POST,PUT,DELETE,OPTIONS,HEAD
    allowedHeaders: origin,content-type,accept,authorization,cookie
  minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
  open-api:
    info:
      title: Keremet Chat api documentation
      description: Full documentation of Keremet chat
      version: v0.0.1-SNAPSHOT
  websocket:
    allowed-origins: 'http://localhost:5173/'
  security:
    default-admin:
      email: 'keremetchatadmin@gmail.com'
      password: 'keremetchatadmin'

springdoc:
  show-oauth2-endpoints: true

management:
  endpoints:
    web.exposure.include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}