server:
  port: 9000

logging:
  level:
    org.springframework:
      web: DEBUG
      security: trace

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            provider: github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
