server:
  port: 9000

logging:
  level:
    org.springframework:
      web: DEBUG
      security: trace

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  freemarker:
    template-loader-path: classpath:/templates/email/
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: 3600000
  session:
    timeout: 43200m


  mail:
    sender:
      address: todo@gmail.com
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    database-change-log-lock-table: db_changelog_lock
    database-change-log-table: db_changelog
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
    contexts: test
  security:
    oauth2:
      client:
        registration:
          github:
            provider: github
            client-name: GitHub
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
        provider:
          github:
            user-name-attribute: login
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/keremet_chat

app:
  jwt:
    secret: ${JWT_SECRET:8ea3d739671fc877d8810dac1fdc69bb93b60ba23b287f5d767ba46373eac681}
    expiration: ${JWT_EXPIRATION:108000000}
  otp:
    expiration: ${OTP_EXPIRATION:5m} # 5 minutes


cors:
  allowCredentials: true
  allowedOrigins: 'http://localhost:5173/'
  allowedMethods: GET,POST,PUT,DELETE,OPTIONS,HEAD
  allowedHeaders: origin,content-type,accept,authorization,cookie


management:
  endpoints:
    web.exposure.include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}