global:
  scrape_interval:     10s
  evaluation_interval: 10s
#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets: []
#      scheme: http
#      timeout: 10s
#      api_version: v1
scrape_configs:
  - job_name: 'keremet-chat-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'Keremet chat application'