apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keremet-chat
  template:
    metadata:
      labels:
        app: keremet-chat
    spec:
      containers:
        - name: app
          image: daneker/keremet-chat
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/keremet_chat
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: keremet-chat
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80