apiVersion: 1

datasources:
  - name: DS_PROMETHEUS
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    uid: DS_PROMETHEUS
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m